version: "3.6"

services:
  app:
    build: ./docker/app
    volumes:
      - ./server:/var/www

  nginx:
    image: nginx
    ports:
      - 80:80
      - 8000:8000
    volumes:
      - ./server:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    # Dockerfileの相対Path
    build: docker/db/
    # build後も使用出来る環境変数としてパスワードを設定
    environment:
      MYSQL_ROOT_PASSWORD: password
    # データの保存場所を設定
    volumes:
      - "mysql-data:/var/lib/mysql"
    ports:
      - 3306:3306
volumes:
  mysql-data: